api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: [ 'application/json' ]


    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
