version: '3'

services:
  server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    volumes:
      - .:/srv/app
    links:
      - php
    ports:
      - '8888:80'

  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: php_dev
    volumes:
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.config/composer:/home/prod/.composer
      - .:/srv/app

  database:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_USERNAME: root
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: planigo
    ports:
      - "3306:3306"
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/init-000.sql
      - ./migrations/data.sql:/docker-entrypoint-initdb.d/init-002.sql
      - ./migrations/triggers.sql:/docker-entrypoint-initdb.d/init-001.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1080:1080"]
  ###< symfony/mailer ###

volumes:
  database_data:
